language: python

env:
  - COVERALLS_PARALLEL=true

matrix:
    include:
        - os: linux
          python: 3.7
          dist: xenial
          sudo: required
        - os: linux
          python: 3.6
          sudo: required
        - os: linux
          python: 2.7
          sudo: required

install:
  - set -e
  - .travis/install.sh

script:
  - set -e
  - nosetests -sv --with-coverage --exclude mlens/visualization --exclude mlens/externals

after_success:
  - coveralls
